config/routes.rb
Rails.application.routes.draw do
  resources :tickets # This adds all the paths at once: edit, new, destroy, show.
  root 'tickets#index'
  devise_for :users, controllers: {
    passwords: 'passwords',
    registrations: 'registrations',
    sessions: 'sessions'
  }
  
  resource :two_factor_settings, except: [:index, :show] do
    member do
      post :download, to: 'two_factor_settings#generateFile'
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :user, optional: true
    enum :status, {
        :open => 1,
        :hold => 2,
        :closed => 3
    }

    enum :priority, {
        :low => 1,
        :medium => 2,
        :high => 3,
        :urgent => 4
    }    
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  def index
    @tickets = Ticket.all.order('status ASC').order('priority DESC')
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = current_user.id

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:title, :content, :label, :status, :priority, :user_id, :first_name, :last_name, :surname_prefix)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= simple_form_for(@ticket) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :label %>
    <%= f.select :status, Ticket.statuses.keys.map { |value| [value.humanize, value] } %>
    <%= f.select :priority, Ticket.priorities.keys.map { |value| [value.humanize, value]} %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<div id="<%= dom_id ticket %>">
<%= link_to [ticket, anchor: :id], class: "nostyle" do %>
  <div class="fluid-container mb-3 ticket-container" >
    <div class="row align-items-center rounded shadow-sm m-0 <%= ticket.priority.downcase+"_priority" %>">      
    <div class="col-1">
        <%= image_tag(ticket.user.avatar_thumbnail, class: "profile_image text-center") %>
      </div> 

      <div class="col">
      <div class="row w-85">
        <div class="col-12 my-auto">
          <span class="my-auto"><strong>#<%= ticket.id %></strong> <%= truncate(ticket.title.humanize, :length => 50) %> <span class="rounded-circle <%= "#{ticket.status.downcase}_status" %>" title="<%= ticket.status.humanize %>">&#8226;</span></span>
        </div>

<div class="row" >
      <div class="col-4">
        <p class="font-weight-light small">
          <strong>Medewerker</strong> <span class="text-secondary"><%= ticket.user.first_name + " " + ticket.user.last_name[0] + "." %></span>
        </p>
      </div>

      <div class="col-7">
        <p class="badge bg-light text-dark">
          <%= ticket.label %>
        </p>
      </div>

      <div class="col-1">
        <p class="text-secondary font-weight-light small">
          <%= ticket.created_at.strftime("%d/%m/%Y") %>
        </p>
      </div>
  </div>
  </div>
  <% end %>


</div>
</div>
</div>

app/views/tickets/edit.html.erb
<h1>Veranderen: ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Show this ticket", @ticket %> |
  <%= link_to "Back to tickets", tickets_path %>
</div>

app/views/tickets/index.html.erb
<div class="w-75">
<p style="color: green"><%= notice %></p>

<%= link_to "Maak een nieuwe ticket aan", new_ticket_path, class: "btn btn-primary mb-2 m-2" %>

<div id="tickets" class="m-2">
  <% @tickets.each do |ticket| %>
    <%= render ticket %>
  <% end %>
</div>
</div>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render "form", ticket: @ticket %>

<br>

<div>
  <%= link_to "Terug naar alle tickets", tickets_path %>
</div>

app/views/tickets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ticket %>

<div>
  <%= link_to "Verander ticket", edit_ticket_path(@ticket) %> |
  <%= link_to "Terug naar alle tickets", tickets_path %>

  <%= button_to "Verwijder deze ticket", @ticket, method: :delete, class: "btn btn-danger" %>
</div>