config/routes.rb
Rails.application.routes.draw do
  resources :tickets # This adds all the paths at once: edit, new, destroy, show.
  root 'tickets#index'
  devise_for :users, controllers: {
    passwords: 'passwords',
    registrations: 'registrations',
    sessions: 'sessions'
  }
  
  resource :two_factor_settings, except: [:index, :show] do
    member do
      post :download, to: 'two_factor_settings#generateFile'
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/two_factor_settings_controller.rb
# method [authenticate_user] they main "variable" that explains that you use the "user class"
# @note  globalvar [current_user] the function from devise that is for the user
class TwoFactorSettingsController < ApplicationController

  before_action :authenticate_user!


  # Makes sure the user can't do it twice to
  # 1 make a new 2 step connection
  # 2 is you have it send you to the backup code form

  # @param method [otp_required_for_login] is a function from devise
  # @return send to edit (backup code page)
  # @return generate_two_factor_secret_if_missing! the bang method (!) makes sure that the value is changed at this point from what is gets.
  def new
    if current_user.otp_required_for_login
      flash[:alert] = 'Two Factor Authentication is already enabled.'
      return redirect_to edit_user_registration_path
    end

    current_user.generate_two_factor_secret_if_missing!
  end

  # @param method [valid_password?] is a method from de otp_password check. it check if the password is correct that has been putin
  # @param var [enable_2fa_params] what is it.
  #  password is the password put in the form field password.
  #  code is the code put in the form field code.
  # @param method [validate_and_consume_otp] checks if the code is correct and use it
  # @return render the new page two times
  # @return send to edit (backup code page)
  # @return set enable_two_factor to true

  def create
    unless current_user.valid_password?(enable_2fa_params[:password])
      flash.now[:alert] = 'Incorrect password'
      return render :new
    end

    if current_user.validate_and_consume_otp!(enable_2fa_params[:code])
      current_user.enable_two_factor!

      flash[:notice] = 'Successfully enabled two factor authentication, please make note of your backup codes.'
      redirect_to edit_two_factor_settings_path
    else
      flash.now[:alert] = 'Incorrect Code'
      render :new
    end
  end

  # edit is they page for showing the backup codes. so everything here has to do with the backup code list.
  # @param method [otp_required_for_login] checks if you have OTP activated
  # @return go to the activate page
  # @param method [two_factor_backup_codes_generated] check if the backup code are there so yes than say that
  # @return go to account settingen edit page.
  #
  # @return else generate backup codes and save thos for user

  def edit
    unless current_user.otp_required_for_login
      flash[:alert] = 'Please enable two factor authentication first.'
      return redirect_to new_two_factor_settings_path
    end

    # if current_user.two_factor_backup_codes_generated?
    #   flash[:alert] = 'You have already seen your backup codes.'
    #   return redirect_to edit_user_registration_path
    # end

    @backup_codes = current_user.generate_otp_backup_codes!
    current_user.save!
  end

  def generateFile
    @data = restyle_backup
    send_data( @data, disposition: "attachment", filename: "backup_code.txt", type: "text/plain")
  end

  def destroy
    if current_user.disable_two_factor!
      flash[:notice] = 'Successfully disabled two factor authentication.'
      redirect_to edit_user_registration_path
    else
      flash[:alert] = 'Could not disable two factor authentication.'
      redirect_back fallback_location: root_path
    end
  end

  private

  def enable_2fa_params
    params.require(:two_fa).permit(:code, :password)
  end

  def restyle_backup
    @styleone = params[:backup_codes]
    @styletwo = @styleone.map { |i| "'" + i.to_s + "'" }.join(",")
    @styletwo.delete!("\n")
    @styletwo.delete!("'")
    @styletwo.gsub!(/,/, "\n")
    return @styletwo
  end

end

app/views/two_factor_settings/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Two Factor Authentication</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card-deck">
        <div class="card">
          <div class="card-header">
            Backup Codes
          </div>
          <div class="card-body">
            <p>Keep these backup codes safe in case you lose access to your authenticator app:</p>
            <hr />
            <% @backup_codes.each_slice(2) do |(code1, code2)| %>
              <div class="row">
                <div class="col-6 text-monospace strong"><%=code1 %></div>
                <div class="col-6 text-monospace strong"><%=code2 %></div>
              </div>
            <% end %>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            Download backup_codes
          </div>
          <div class="card-body">
            <p>Two factor authentication has been successfully enabled.</p>
                        <%= button_to(
                    "Log Out",
                    destroy_user_session_path,
                    class: 'btn btn-primary',
                    method: :delete
                  ) %>
            <%= button_to('download', download_two_factor_settings_path, class: 'btn btn-primary', data: {turbo: false},  params: {:backup_codes => @backup_codes}) %>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            Two Factor Setup Complete
          </div>
          <div class="card-body">
            <p>Two factor authentication has been successfully enabled.</p>
            <%= link_to('Return to account settings', edit_user_registration_path, class: 'btn btn-primary') %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/two_factor_settings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Two Factor Authentication</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="card-deck">
        <div class="card">
          <div class="card-header">
            1. Scan QR Code
          </div>
          <div class="card-body">
            <p>Please scan the below QR code using an OTP compatible app (such as Google Authenticator or Authy).</p>
            <hr />
            <p class="text-center">
              <%= qr_code_as_svg(current_user.two_factor_qr_code_uri)%>
            </p>
            <hr />
            <p class="text-center">
              If you cannot scan, please enter the following code manually: <code><%= current_user.otp_secret%></code>
            </p>
          </div>
        </div>
        <div class="card">
          <div class="card-header">
            2. Confirm OTP Code
          </div>
          <div class="card-body">
            <p>Please confirm that your authentication application is working by entering a generated code below.</p>
            <%= simple_form_for(:two_fa, url: two_factor_settings_path, method: :post) do |f| %>
            <%= f.input :code %>
            <%= f.input :password, label: 'Enter your current password' %>
            <%= f.submit 'Confirm and Enable Two Factor', class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>